backend:
  name: git-gateway
collections:
  - name: "yarnlings"
    label: "Yarnlings"
    folder: "content/yarnlings"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}

